services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: identity_service
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    # Đã bỏ healthcheck ở đây

  springboot-app:
    build: .
    container_name: springboot_container
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_container:3306/identity_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql  # Dùng kiểu đơn giản, không kiểm tra health

volumes:
  mysql_data:
