spring:
  datasource:
    url: "jdbc:mysql://mysql:3306/identity_service"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  lifecycle:
    timeout-per-shutdown-phase: 30s